CREATE TABLE [dbo].[organdonor] (
    [Id]            INT           IDENTITY (1, 1) NOT NULL,
    [ft_name]       VARCHAR (30)  NOT NULL,
    [md_name]       VARCHAR (30)  NOT NULL,
    [lt_name]       VARCHAR (30)  NOT NULL,
    [m_f_name]      VARCHAR (50)  NOT NULL,
    [d_address]     VARCHAR (150) NOT NULL,
    [d_city]        VARCHAR (30)  NOT NULL,
    [d_district]    VARCHAR (30)  NOT NULL,
    [d_state]       VARCHAR (30)  NOT NULL,
    [d_pincode]     INT           NOT NULL,
    [d_mobileno]    BIGINT        NOT NULL,
    [d_occupation]  VARCHAR (50)  NOT NULL,
    [d_email]       VARCHAR (50)  NOT NULL,
    [d_dob]         DATE          NOT NULL,
    [d_age]         INT           NOT NULL,
    [d_gender]      VARCHAR (20)  NOT NULL,
    [d_blood_grp]   VARCHAR (20)  NOT NULL,
    [identity_card] VARCHAR (20)  NOT NULL,
    [identity_no]   VARCHAR (15)  NOT NULL,
    [organ_chb]     VARCHAR (500) NOT NULL,
    [emg_nm]        VARCHAR (30)  NOT NULL,
    [emg_no]        BIGINT        NOT NULL,
    [emg_add]       VARCHAR (150) NOT NULL,
    [hear_d]        VARCHAR (80)  NOT NULL,
    CONSTRAINT [PK_organdonor] PRIMARY KEY CLUSTERED ([Id] ASC)
);
